---

###########################################################################
### OpenShift Metrics and Logging Vars
###########################################################################

# Enable cluster metrics

openshift_metrics_install_metrics: 'True' 

openshift_metrics_storage_kind: 'nfs' 
openshift_metrics_storage_access_modes: 
  - 'ReadWriteOnce' 
openshift_metrics_storage_nfs_directory: '/srv/nfs'
openshift_metrics_storage_host: 'support1.9e95.internal'
openshift_metrics_storage_nfs_options: '*(rw,root_squash)' 
openshift_metrics_storage_volume_name: 'metrics' 
openshift_metrics_storage_volume_size: '10Gi'
openshift_metrics_storage_labels: 
  storage: "metrics"
openshift_metrics_cassandra_nodeselector: 
  env: "infra"
openshift_metrics_hawkular_nodeselector: 
  env: "infra"
openshift_metrics_heapster_nodeselector: 
  env: "infra"

# Enable cluster logging

openshift_logging_install_logging: 'True' 

openshift_logging_storage_kind: 'nfs'
openshift_logging_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_logging_storage_nfs_directory: '/srv/nfs' 
openshift_logging_storage_host: 'support1.9e95.internal'
openshift_logging_storage_nfs_options: '*(rw,root_squash)' 
openshift_logging_storage_volume_name: 'logging'
openshift_logging_storage_volume_size: '10Gi' 
openshift_logging_storage_labels: 
  storage: "logging" 

# openshift_logging_kibana_hostname: kibana.apps.9e95.example.opentlc.com
openshift_logging_es_cluster_size: 1

openshift_logging_es_nodeselector: 
  env: "infra"
openshift_logging_kibana_nodeselector: 
  env: "infra"
openshift_logging_curator_nodeselector: 
  env: "infra" 
