---

## Add Prometheus Metrics:
openshift_hosted_prometheus_deploy: 'true'
openshift_prometheus_node_selector: 
  env: "infra"
openshift_prometheus_namespace: 'openshift-metrics' 

# Prometheus

openshift_prometheus_storage_kind: 'nfs'
openshift_prometheus_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_prometheus_storage_nfs_directory: '/srv/nfs'
openshift_prometheus_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_storage_volume_name: 'prometheus'
openshift_prometheus_storage_volume_size: '10Gi'
openshift_prometheus_storage_labels: 
  storage: "prometheus"
openshift_prometheus_storage_type: 'pvc'
# For prometheus-alertmanager
openshift_prometheus_alertmanager_storage_kind: 'nfs'
openshift_prometheus_alertmanager_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_prometheus_alertmanager_storage_nfs_directory: '/srv/nfs'
openshift_prometheus_alertmanager_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_alertmanager_storage_volume_name: 'prometheus-alertmanager'
openshift_prometheus_alertmanager_storage_volume_size: '10Gi'
openshift_prometheus_alertmanager_storage_labels: 
  storage: "prometheus-alertmanager"
openshift_prometheus_alertmanager_storage_type: 'pvc'
# For prometheus-alertbuffer
openshift_prometheus_alertbuffer_storage_kind: 'nfs'
openshift_prometheus_alertbuffer_storage_access_modes: 
  - 'ReadWriteOnce'
openshift_prometheus_alertbuffer_storage_nfs_directory: '/srv/nfs'
openshift_prometheus_alertbuffer_storage_nfs_options: '*(rw,root_squash)'
openshift_prometheus_alertbuffer_storage_volume_name: 'prometheus-alertbuffer'
openshift_prometheus_alertbuffer_storage_volume_size: '10Gi'
openshift_prometheus_alertbuffer_storage_labels: 
  storage: "prometheus-alertbuffer"
openshift_prometheus_alertbuffer_storage_type: 'pvc'
